import requests

f= open("results.txt","w")

with open("urls.txt", "r") as file:
	for url in file:
		url = url.rstrip("\n")
		exts=('/')
		print ('[+] Scanning ' + url + ' for Sub-Domain Takeover' )
		for ext in exts:
			url1=url+ext
			try:
				url2 = "http://"+url1
				domain = requests.get(url2 , timeout=5)
				if 'NoSuchBucket' in domain.text :
					print 'S3 Bucket Found'
					f.write(str(url2) + '<====>' + 'S3 Bucket Found')
				elif 'Domain mapping upgrade for this domain not found. Please log in and go to the Domains Upgrades page of your blog to use this domain' in domain.text :
					print 'Wordpress Site Found'
					f.write(str(url2) + '<====>' + 'Wordpress Site Found')
				elif 'There is no app configured at that hostname' in domain.text :
					print 'Heroku Sub-Domain'
					f.write(str(url2) + '<====>' + 'Heroku Subdomain Found')
				elif 'No Such Account' in domain.text :
					print 'SquareSpace Account'
					f.write(str(url2) + '<====>' + 'SquareSpace Account Found')
				elif "You're Almost There" in domain.text :
					print 'SquareSpace Account'
					f.write(str(url2) + '<====>' + 'SquareSpace Account Found')
				elif "There isn't a GitHub Pages site here" in domain.text :
					print 'GitHub Page'
					f.write(str(url2) + '<====>' + 'GitHub Page Found')
				elif "Sorry, this shop is currently unavailable." in domain.text :
					print 'Shopify Account'
					f.write(str(url2) + '<====>' + 'Shopify Account Found')
				elif "There's nothing here." in domain.text :
					print 'Tumbler Account'
					f.write(str(url2) + '<====>' + 'Tumbler Account Found')
				elif "The site you were looking for couldn't be found." in domain.text :
					print 'Wp-Engine Account'
					f.write(str(url2) + '<====>' + 'Wp-Engine Found')
				elif "Please check that this domain has been added to a service." in domain.text :
					print 'Fastly Account'
					f.write(str(url2) + '<====>' + 'Fastly Account Found')
				elif "This UserVoice subdomain is currently available" in domain.text :
					print 'UserVoice Account'
					f.write(str(url2) + '<====>' + 'UserVoice Account Found')
				elif "404. That's an error" in domain.text :
					print 'Google Account'
					f.write(str(url2) + '<====>' + 'Google Account Found')
				elif "Generated by cloudfront" in domain.text :
					print 'CloudFront Found'
					f.write(str(url2) + '<====>' + 'CloudFront Account Found')
				elif 'Trying to access your account?' in domain.text :
					print 'Campaign Monitor Found'
					f.write(str(url2) + '<====>' + 'Campaign Monitor Found')
				elif 'Use a personal domain name' in domain.text :
					print 'CargoCollective Found'
					f.write(str(url2) + '<====>' + 'CargoCollective Found')
				elif "Sorry, We Couldn't Find That Page" in domain.text :
					print 'Desk Subdomain Found'
					f.write(str(url2) + '<====>' + 'Desk Subdomain Found')
				elif "The feed has not been found." in domain.text :
					print 'FeedPress Subdomain Found'
					f.write(str(url2) + '<====>' + 'FeedPress Subdomain Found')
				elif 'You can claim it now at' in domain.text :
					print 'FreshDesk Found'
					f.write(str(url2) + '<====>' + 'FreshDesk Found')
				elif "The thing you were looking for is no longer here, or never was" in domain.text :
					print 'Ghost.io Found'
					f.write(str(url2) + '<====>' + 'Ghost.io Found')
				elif "No such app" in domain.text :
					print 'HelpJuice Subdomain Found'
					f.write(str(url2) + '<====>' + 'HelpJuice Subdomain Found')
				elif "No settings were found for this company" in domain.text :
					print 'Help Scout Docs Subdomain Found'
					f.write(str(url2) + '<====>' + 'Help Scout Docs Subdomain Found')
				elif 'Help Center Closed | Zendesk' in domain.text :
					print 'Zendesk Found'
					f.write(str(url2) + '<====>' + 'Zendesk Found')
				elif "The requested URL was not found on this server." in domain.text :
					print 'UnBounce Pages Found'
					f.write(str(url2) + '<====>' + 'UnBounce Pages Found')
				elif 'class="MarketplaceHeader__tictailLogo"' in domain.text :
					print 'TicTail Subdomain Found'
					f.write(str(url2) + '<====>' + 'TicTail Subdomain Found')
				elif "Oops - We didn't find your site." in domain.text :
					print 'TeamWork Subdomain Found'
					f.write(str(url2) + '<====>' + 'TeamWork Subdomain Found')
				elif 'data-html-name="Header Logo Link"' in domain.text :
					print 'Survey Gizmo Subdomain Found'
					f.write(str(url2) + '<====>' + 'Survey Gizmo Subdomain Found')
				elif 'Hosted Status Pages for Your Company' in domain.text :
					print 'Status Pages Found'
					f.write(str(url2) + '<====>' + 'Status Pages Found')
				elif "Sorry, couldn&rsquo;t find the status page" in domain.text :
					print 'PingDom Subdomain Found'
					f.write(str(url2) + '<====>' + 'PingDom Subdomain Found')
			except:
				pass
			try:
				url3 = "https://"+url1
				domain1 = requests.get(url3 , timeout=5)
				if  'NoSuchBucket' in domain.text:
					print 'S3 Bucket Found'
					f.write(str(url3) + '<====>' + 'S3 Bucket Found')
				elif 'Domain mapping upgrade for this domain not found. Please log in and go to the Domains Upgrades page of your blog to use this domain' in domain.text :
					print 'Wordpress Site Found'
					f.write(str(url2) + '<====>' + 'Wordpress Site Found')
				elif 'There is no app configured at that hostname' in domain.text :
					print 'Heroku Sub-Domain'
					f.write(str(url2) + '<====>' + 'Heroku Subdomain Found')
				elif 'No Such Account' in domain.text :
					print 'SquareSpace Account'
					f.write(str(url2) + '<====>' + 'SquareSpace Account Found')
				elif "You're Almost There" in domain.text :
					print 'SquareSpace Account'
					f.write(str(url2) + '<====>' + 'SquareSpace Account Found')
				elif "There isn't a GitHub Pages site here" in domain.text :
					print 'GitHub Page'
					f.write(str(url2) + '<====>' + 'GitHub Page Found')
				elif "Sorry, this shop is currently unavailable." in domain.text :
					print 'Shopify Account'
					f.write(str(url2) + '<====>' + 'Shopify Account Found')
				elif "There's nothing here." in domain.text :
					print 'Tumbler Account'
					f.write(str(url2) + '<====>' + 'Tumbler Account Found')
				elif "The site you were looking for couldn't be found." in domain.text :
					print 'Wp-Engine Account'
					f.write(str(url2) + '<====>' + 'Wp-Engine Found')
				elif "Please check that this domain has been added to a service." in domain.text :
					print 'Fastly Account'
					f.write(str(url2) + '<====>' + 'Fastly Account Found')
				elif "This UserVoice subdomain is currently available" in domain.text :
					print 'UserVoice Account'
					f.write(str(url2) + '<====>' + 'UserVoice Account Found')
				elif "404. That's an error" in domain.text :
					print 'Google Account'
					f.write(str(url2) + '<====>' + 'Google Account Found')
				elif "Generated by cloudfront" in domain.text :
					print 'CloudFront Found'
					f.write(str(url2) + '<====>' + 'CloudFront Account Found')
				elif 'Trying to access your account?' in domain.text :
					print 'Campaign Monitor Found'
					f.write(str(url2) + '<====>' + 'Campaign Monitor Found')
				elif 'Use a personal domain name' in domain.text :
					print 'CargoCollective Found'
					f.write(str(url2) + '<====>' + 'CargoCollective Found')
				elif "Sorry, We Couldn't Find That Page" in domain.text :
					print 'Desk Subdomain Found'
					f.write(str(url2) + '<====>' + 'Desk Subdomain Found')
				elif "The feed has not been found." in domain.text :
					print 'FeedPress Subdomain Found'
					f.write(str(url2) + '<====>' + 'FeedPress Subdomain Found')
				elif 'You can claim it now at' in domain.text :
					print 'FreshDesk Found'
					f.write(str(url2) + '<====>' + 'FreshDesk Found')
				elif "The thing you were looking for is no longer here, or never was" in domain.text :
					print 'Ghost.io Found'
					f.write(str(url2) + '<====>' + 'Ghost.io Found')
				elif "No such app" in domain.text :
					print 'HelpJuice Subdomain Found'
					f.write(str(url2) + '<====>' + 'HelpJuice Subdomain Found')
				elif "No settings were found for this company" in domain.text :
					print 'Help Scout Docs Subdomain Found'
					f.write(str(url2) + '<====>' + 'Help Scout Docs Subdomain Found')
				elif 'Help Center Closed | Zendesk' in domain.text :
					print 'Zendesk Found'
					f.write(str(url2) + '<====>' + 'Zendesk Found')
				elif "The requested URL was not found on this server." in domain.text :
					print 'UnBounce Pages Found'
					f.write(str(url2) + '<====>' + 'UnBounce Pages Found')
				elif 'class="MarketplaceHeader__tictailLogo"' in domain.text :
					print 'TicTail Subdomain Found'
					f.write(str(url2) + '<====>' + 'TicTail Subdomain Found')
				elif "Oops - We didn't find your site." in domain.text :
					print 'TeamWork Subdomain Found'
					f.write(str(url2) + '<====>' + 'TeamWork Subdomain Found')
				elif 'data-html-name="Header Logo Link"' in domain.text :
					print 'Survey Gizmo Subdomain Found'
					f.write(str(url2) + '<====>' + 'Survey Gizmo Subdomain Found')
				elif 'Hosted Status Pages for Your Company' in domain.text :
					print 'Status Pages Found'
					f.write(str(url2) + '<====>' + 'Status Pages Found')
				elif "Sorry, couldn&rsquo;t find the status page" in domain.text :
					print 'PingDom Subdomain Found'
					f.write(str(url2) + '<====>' + 'PingDom Subdomain Found')
			except:
				pass
f.close
print ('Scanning Completed, vulnerable url list stored in results.txt file')
f.close